In [ ]:


from helpers.mysql_connections import create_mysql_engine

import pandas as pd
import matplotlib.pyplot as plt

engine = create_mysql_engine()

query = 'SELECT * FROM results'
df_results = pd.read_sql( query, engine )
df_results.head(5)

,id,campaign_id,user_id,r_id,email,first_name,last_name,status,ip,latitude,longitude,position,send_date,reported,modified_date
0,1,101,1,AzK6Fg,andresrosales1@corpnet.com,Andres,Rosales,Clicked Link,172.219.4.215,13.678529,-89.248728,Estudiante,2026-03-15 14:07:00,0,2026-03-15 14:15:43
1,2,101,1,MKrJE7,roberto.escobar2@servicios.local,Roberto,Escobar,Email Opened,171.72.253.37,13.765087,-89.130911,Estudiante,2026-03-15 23:33:00,0,2026-03-15 23:40:48
2,3,101,1,itc3EV,andrescortez3@techzone.io,Andres,Cortez,Email Opened,181.252.57.239,13.779004,-89.264338,Estudiante,2026-03-15 20:01:00,0,2026-03-15 20:09:37
3,4,101,1,3hKdJy,adrian.padilla4@campusmail.edu,Adrian,Padilla,Email Opened,187.212.105.99,13.644827,-89.148701,Estudiante,2026-03-15 20:13:00,0,2026-03-15 20:16:33
4,5,101,1,LK9bHL,oscarpadilla5@techzone.io,Oscar,Padilla,Clicked Link,182.6.70.98,13.817546,-89.154148,Estudiante,2026-03-15 21:59:00,0,2026-03-15 22:00:49

In [14]:

## Porcentage of emails with URL clicked

q_url_clicked = 'SELECT * FROM results WHERE status = "Clicked Link"'
## Total of emails

total_emails = len(df_results)

## Number of emails with URLs that were clicked

df_emails_url_clicked= pd.read_sql( q_url_clicked, engine )
emails_url_clicked = len(df_emails_url_clicked)

## Metrics Calculations

emails_with_url_clicked_index = round( emails_url_clicked / total_emails, 3)

emails_with_url_clicked_prtg = round( emails_url_clicked / total_emails * 100,2)

other_emails_prtg = round( ( total_emails - emails_url_clicked ) / total_emails * 100,2)

emails_emails_url_clicked_dict = {
    'Emails with URL Clicked': [emails_url_clicked],
    'Index' : [emails_with_url_clicked_index],
    '%': [f'{emails_with_url_clicked_prtg}%'],
    'Other Emails %': [f'{other_emails_prtg}%']
}


df_emails_url_clicked = pd.DataFrame( emails_emails_url_clicked_dict, index= ['Values'], columns = ['Emails with URL Clicked', 'Index', '%', 'Other Emails %']  )

---

# **Presentacion de la Informacion**

---

In [15]:
display( df_emails_url_clicked )

        Emails with URL Clicked  Index      % Other Emails %
Values                      177  0.354  35.4%          64.6%

In [ ]:
labels = ['Emails con URLs accedidos', 'Otros emails']
values = [emails_with_url_clicked_prtg, other_emails_prtg]
colors = ["#FF7777", "#78D666"]

plt.pie( values, labels=labels, colors=colors,  autopct='%1.1f%%')

plt.title('Total de Emails Abiertos - Reportados y no Reportados como Phishing')
plt.axis('equal')

plt.show()